version: '3'
services:    
  client:
    build: .
    volumes:
      - ./client:/home/app/client
    working_dir: /home/app/client
    command: npm install
  server:
    build: .
    volumes:
      - ./server:/home/app/server
    working_dir: /home/app/server
    command: npm install