version: '2'
services:
  base:
    image: node:11
    volumes:
      - .:/home/app/
    working_dir: /home/app/
  install:
    extends:
      service: base
    command: npm i
  build:
    extends:
      service: base
    command: npm run build